Repository fedora-infra/bodhi, pull requests merged in 2018-07, with the labels that each got.

#2477 Prepare the 3.9.0 release.
  docs/conf.py
  docs/user/release_notes.rst
  setup.py
Labels: Docs, High priority

#2478 Use the correct format for return type in a docblock.
  bodhi/server/models.py
Labels: Crash, Critical, Docs

#2502 Install python2-backports-functools_lru_cache in Rawhide CI.
  devel/ci/rawhide-packages
Labels: 3.9-backports, Crash, Critical, Tests

#2497 Prevent password prompt for 'bodhi releases' command.
  bodhi/client/__init__.py
Labels: 3.9-backports

#2488 Fix listing the missing requirements in bodhi-client
  bodhi/client/__init__.py
  bodhi/tests/client/test___init__.py
Labels: 3.9-backports

#2493 Raise line coverage to 100%.
  .coveragerc
  bodhi/server/models.py
  bodhi/tests/server/consumers/test_masher.py
  bodhi/tests/server/test_models.py
Labels: Tests

#2495 Change the '--username' option to '--user' for 'bodhi release'.
  bodhi/client/__init__.py
  bodhi/server/scripts/manage_releases.py
  bodhi/tests/client/test___init__.py
  bodhi/tests/server/scripts/test_manage_releases.py
Labels: 3.9-backports

#2435 Fix editing multi-build updates when title failed to update
  bodhi/server/validators.py
  bodhi/tests/server/services/test_updates.py
Labels: Critical, WebUI, reliability

#2484 Add support to filter releases by state in the JSON API
  bodhi/server/schemas.py
  bodhi/server/services/releases.py
  bodhi/tests/server/services/test_releases.py
Labels: API

#2482 Don't require notes when --file is used in the CLI.
  bodhi/client/__init__.py
  bodhi/tests/client/test___init__.py
Labels: 3.9-backports, Client, Critical
