Repository fedora-infra/bodhi, pull requests merged in 2018-05, with the labels that each got.

#2332 Remove support for str arguments from util.cmd().
  bodhi/server/util.py
  bodhi/tests/server/test_util.py
Labels: Refactor, reliability

#2339 Remove update category batching
  bodhi/server/consumers/masher.py
Labels: Composer, Performance

#2345 Store greenwave's unsatisfied requirements in its own db column.
  bodhi/server/migrations/versions/59c0f5fbc1b2_add_a_greenwave_unsatisfied_.py
  bodhi/server/models.py
  bodhi/server/templates/update.html
  bodhi/server/util.py
  bodhi/tests/server/consumers/test_updates.py
  bodhi/tests/server/scripts/test_check_policies.py
  bodhi/tests/server/test_models.py
  bodhi/tests/server/test_util.py
Labels: Crash, Critical, Migration, Refactor

#2352 [BACKPORT] Store greenwave's unsatisfied requirements in its own db column.
  bodhi/server/migrations/versions/59c0f5fbc1b2_add_a_greenwave_unsatisfied_.py
  bodhi/server/models.py
  bodhi/server/templates/update.html
  bodhi/server/util.py
  bodhi/tests/server/consumers/test_updates.py
  bodhi/tests/server/scripts/test_check_policies.py
  bodhi/tests/server/test_models.py
  bodhi/tests/server/test_util.py
Labels: Tests

#2348 Extend the 3.7.0 release notes.
  docs/user/release_notes.rst
Labels: Critical, Docs

#2346 Do not allow updates to be pushed if they fail the gating check.
  bodhi/server/models.py
  bodhi/server/templates/update.html
  bodhi/tests/server/consumers/test_masher.py
  bodhi/tests/server/services/test_updates.py
  bodhi/tests/server/test_models.py
Labels: Critical

#2353 [BACKPORT] Add new privacy_link and legal_link settings.
  bodhi/server/config.py
  bodhi/server/templates/master.html
  bodhi/server/templates/update.html
  bodhi/tests/server/services/test_updates.py
  production.ini
Labels: Tests

#2354 [BACKPORT] Extend the 3.7.0 release notes.
  docs/user/release_notes.rst
Labels: Tests

#2359 [BACKPORT] Move the greenwave_unsatisfied_requirements migration to be next.
  bodhi/server/migrations/versions/59c0f5fbc1b2_add_a_greenwave_unsatisfied_.py
Labels: Tests

#2366 [BACKPORT] Print javascript for waiverdb info
  bodhi/server/templates/update.html
Labels: Tests

#2377 Prepare the 3.8.0 release.
  docs/conf.py
  docs/user/release_notes.rst
  setup.py
Labels: Docs, High priority

#2381 Do not apply Koji tags to ejected updates.
  bodhi/server/buildsys.py
  bodhi/server/consumers/masher.py
  bodhi/server/models.py
  bodhi/tests/server/consumers/test_masher.py
  bodhi/tests/server/test_models.py
Labels: Composer, Crash, Critical, reliability

#2382 Add a release note for #2368.
  docs/user/release_notes.rst
Labels: Critical, Docs
