Repository fedora-infra/bodhi, pull requests merged in 2018-11, with the labels that each got.

#2718 Adjust production.ini to account for % interpolation in Python 3.
  production.ini
Labels: 3.11-backports, Crash, High priority

#2712 Use the Python 3 version of alembic if available.
  bodhi/tests/server/test_alembic.py
Labels: 3.11-backports, High priority, Refactor, Tests

#2710 jcline did it wrong.
  docs/generate_db_schema
Labels: Refactor

#2708 Simplify the Vagrant playbook by combining the roles.
  devel/ansible/playbook.yml
  devel/ansible/roles/bodhi/files/.bashrc
  devel/ansible/roles/bodhi/files/.vimrc
  devel/ansible/roles/bodhi/files/bodhi.service
  devel/ansible/roles/bodhi/files/fedmsg-tail.service
  devel/ansible/roles/bodhi/files/motd
  devel/ansible/roles/bodhi/tasks/main.yml
  devel/ansible/roles/core/tasks/main.yml
  devel/ansible/roles/db/tasks/main.yml
  docs/developer/vagrant.rst
Labels: Refactor

#2722 Prepare the 3.11.0 release.
  .mergify.yml
  docs/conf.py
  docs/user/release_notes.rst
  setup.py
Labels: Tests

#2723 The 3.11 branch should measure diff against 3.11.
  devel/ci/bodhi-ci
Labels: Crash, Tests

#2711 Use Python 3 when building the docs.
  devel/ansible/roles/bodhi/tasks/main.yml
  devel/ci/Dockerfile-f27
  devel/ci/Dockerfile-f28
  devel/ci/Dockerfile-f29
  devel/ci/Dockerfile-pip
  devel/ci/Dockerfile-rawhide
  docs/Makefile
  docs/generate_db_schema
Labels: 3.11-backports, Docs, High priority, Refactor

#2734 Do not require pyramid_tm.
  devel/development.ini.example
  docs/user/release_notes.rst
  production.ini
  requirements.txt
Labels: 3.11-backports, Crash, Critical

#2733 Default to a JSON response when no accept header is provided.
  bodhi/server/webapp.py
  bodhi/tests/server/base.py
  bodhi/tests/server/functional/test_admin.py
  bodhi/tests/server/functional/test_stacks.py
  bodhi/tests/server/services/test_comments.py
  bodhi/tests/server/services/test_composes.py
  bodhi/tests/server/services/test_overrides.py
  bodhi/tests/server/services/test_releases.py
  bodhi/tests/server/services/test_updates.py
  bodhi/tests/server/test_renderers.py
  bodhi/tests/server/views/test_generic.py
Labels: 3.11-backports, Critical, python3

#2732 Use Python 3 when running Bodhi in Vagrant.
  devel/ansible/roles/bodhi/files/bodhi.service
  devel/ansible/roles/bodhi/tasks/main.yml
Labels: python3

#2669 Install click from EPEL in CI instead of from PyPI.
  devel/ci/cico.pipeline
Labels: RFE, Tests

#2740 Convert subprocess.communicate()'s output to str in the composer.
  bodhi/server/consumers/masher.py
  bodhi/tests/server/consumers/test_masher.py
Labels: 3.11-backports, Composer, Crash, Critical

#2743 Properly parse container pull specs from koji metadata
  bodhi/server/buildsys.py
  bodhi/server/util.py
  bodhi/tests/server/test_util.py
Labels: 3.11-backports, Composer, Crash, Critical

#2747 Don't try to encode() byte arrays.
  bodhi/server/consumers/masher.py
  bodhi/tests/server/consumers/test_masher.py
Labels: 3.11-backports, Composer, Crash, Critical, Tests, python3

#2707 Upgrade the Vagrant environment to Fedora 29.
  Vagrantfile
  devel/ansible/roles/bodhi/tasks/main.yml
Labels: RFE

#2749 Remove some cruft that was needed to run on EL 7.
  apache/bodhi.wsgi
  setup.py
Labels: 3.11-backports, Crash, Critical, python3

#2752 Rawhide py3 only
  devel/ci/Dockerfile-rawhide
  devel/ci/bodhi-ci
Labels: Tests, python3

#2763 Build the docs with Python 3 in CI.
  devel/ci/Dockerfile-rawhide
  devel/ci/bodhi-ci
Labels: Crash, Docs, Tests

#2765 Run diff-cover with just develop instead of origin/develop.
  devel/ci/bodhi-ci
  devel/ci/cico.pipeline
Labels: Refactor, Tests, reliability

#2769 Handle IncompleteRead in the composer when on Python 3.
  bodhi/server/consumers/masher.py
  bodhi/tests/server/consumers/test_masher.py
Labels: 3.11-backports, Composer, Crash, Critical, python3

#2767 Allow EnumSymbols to be sorted.
  bodhi/server/models.py
  bodhi/tests/server/test_models.py
Labels: 3.11-backports, Composer, Crash, Critical, python3

#2766 Prepare the 3.11.1 release.
  docs/conf.py
  docs/user/release_notes.rst
  setup.py
Labels: 3.11-backports, Critical, Docs

#2788 Decode the captcha key so it is a string.
  bodhi/server/captcha.py
  bodhi/tests/server/test_captcha.py
  docs/user/release_notes.rst
Labels: 3.11-backports, Crash, Critical, WebUI, python3

#2797 Fedora 27 is no longer supported.
  .mergify.yml
  devel/ci/Dockerfile-f27
  devel/ci/Dockerfile-pip
  devel/ci/bodhi-ci
  devel/ci/cico.pipeline
Labels: 3.11-backports, Crash, Critical, Tests
