Repository fedora-infra/bodhi, pull requests merged in 2018-06, with the labels that each got.

#2349 Update the copyright in Bodhi's footer.
  bodhi/server/templates/master.html
Labels: HTML, WebUI

#2376 Remove a conflicting HTTPForbidden handler.
  bodhi/server/__init__.py
  devel/ansible/roles/dev/tasks/main.yml
  devel/ci/f26-packages
  devel/ci/f27-packages
  requirements.txt
Labels: API, Crash

#2379 Use the full path when cd'ing to the Bodhi folder in Vagrant.
  devel/ansible/roles/dev/files/.bashrc
Labels: Low Priority

#2378 Throw out composes that have failed the sanity check
  bodhi/server/consumers/masher.py
  bodhi/tests/server/consumers/test_masher.py
Labels: Composer, reliability

#2414 Do not run flake8 on Fedora 29.
  devel/test_container.sh
Labels: Crash, Critical, Tests

#1986 Do not re-compose if the repo is already staged
  bodhi/server/consumers/masher.py
  bodhi/tests/server/consumers/test_masher.py
Labels: Composer, High priority, reliability

#2383 Add 100% Python 2 test coverage for bodhi.server.consumers.masher.
  bodhi/tests/server/consumers/test_masher.py
Labels: Composer, Tests, python3

#2391 Include the waiver API in the server docs.
  docs/server_api/updates.rst
Labels: Critical, Docs, RFE

#2400 Allow Vismay to run CI tests.
  devel/ci/githubprb-project.yml
Labels: Tests

#2408 Increase test coverage on bodhi.server.models.
  bodhi/tests/server/test_models.py
Labels: Tests

#2411 Remove f26 from tests
  devel/ci/f26-packages
  devel/run_tests.sh
Labels: Tests

#2410 Require cornice >= 3.1.0.
  docs/user/release_notes.rst
  requirements.txt
Labels: Critical, Docs

#2404 Add 100% test coverage to bodhi.server.validators.
  bodhi/server/validators.py
  bodhi/tests/server/test_validators.py
Labels: Tests

#2409 Require 99% test coverage.
  .coveragerc
Labels: Tests

#2423 Automatically run CI tests on @owtaylor's PRs.
  devel/ci/githubprb-project.yml
Labels: Tests

#2436 Stop using async as variable name, it's a keyword since Python 3.7
  bodhi/server/util.py
  bodhi/tests/server/test_util.py
Labels: Crash, Critical, python3

#2442 Python 3.7: repr of exceptions changed not to include trailing comma
  bodhi/tests/server/test___init__.py
  bodhi/tests/server/test_mail.py
Labels: Crash, Critical, Tests

#2443 Prepare for the release of 3.8.1.
  docs/conf.py
  docs/user/release_notes.rst
  setup.py
Labels: Docs, High priority

#2447 [BACKPORT] Do not run flake8 on Fedora 29.
  devel/test_container.sh
Labels: Tests

#2445 [Backport] Prepare for the release of 3.8.1.
  docs/conf.py
  docs/user/release_notes.rst
  setup.py
Labels: Tests

#2427 Configure coverage to print the missing lines in the text report.
  .coveragerc
Labels: RFE, Tests

#2449 Install python3-ipdb in Vagrant.
  devel/ansible/roles/dev/tasks/main.yml
Labels: Low Priority, RFE

#2450 Fix a deprecation warning in setup.cfg for pytest.
  setup.cfg
Labels: Low Priority, Refactor

#2451 Use a raw string for a regex to silence a DeprecationWarning.
  bodhi/server/models.py
Labels: Low Priority, Refactor

#2452 Close the alembic history process before finishing the test.
  bodhi/tests/server/test_alembic.py
Labels: Low Priority, Refactor, Tests
