Repository fedora-infra/bodhi, pull requests merged in 2018-12, with the labels that each got.

#2796 Correctly handle IncompleteRead in the Composer.
  bodhi/server/consumers/masher.py
  bodhi/tests/server/consumers/test_masher.py
  docs/conf.py
  docs/user/release_notes.rst
  setup.py
Labels: 3.11-backports, Composer, Crash, Critical, Hotfixed, Tests, python3

#2807 Merge PRs by me when tests pass, or by others when I approve.
  .mergify.yml
Labels: Tests

#2808 Do not use an array for Mergify since that doesn't seem to work.
  .mergify.yml
Labels: Tests

#2755 Do not install pyramid_tm in Vagrant or CI.
  devel/ansible/roles/bodhi/tasks/main.yml
  devel/ci/Dockerfile-f28
  devel/ci/Dockerfile-f29
  devel/ci/Dockerfile-rawhide
Labels: Refactor, Tests

#2795 Correctly skip coverage testing Rawhide with Python 2.
  devel/ci/bodhi-ci
Labels: 3.11-backports, Tests

#2792 Fix javascript code for candidate builds in update form.
  bodhi/server/static/js/update_form.js
Labels: 3.11-backports, High priority, JS, WebUI

#2810 Prepare the 3.11.3 release.
  docs/conf.py
  docs/user/release_notes.rst
  setup.py
Labels: 3.11-backports, Docs, High priority

#2809 Remove old dnf workarounds from the Rawhide Dockerfile.
  devel/ci/Dockerfile-rawhide
Labels: Refactor, Tests

#2816 Remove side_tag_merging from the side tag migration docblock.
  bodhi/server/migrations/versions/22858ba91115_add_new_side_tag_update_states.py
Labels: Docs, Low Priority, Refactor

#2823 Require python3 on the integration tests, not python 2.
  .mergify.yml
Labels: Critical, Tests

#2836 Assert update title instead of build nvr in CLI test output.
  devel/ci/integration/tests/test_bodhi_cli.py
Labels: Crash, Critical, Tests, in progress, reliability

#2831 Log unhandled errors from Bugzilla and expand info on Faults.
  bodhi/server/bugs.py
  bodhi/tests/server/test_bugs.py
Labels: RFE, bugzilla

#2822 Fix the alignment of the status report for bodhi-ci.
  devel/ci/bodhi-ci
Labels: RFE, Tests

#2843 Document Bodhi's use of GitHub labels.
  docs/developer/index.rst
Labels: Docs, in progress

#2857 Add a new backport rule for the 3.12 branch.
  .mergify.yml
Labels: Critical

#2872 Keep the commit we are testing as a branch.
  devel/ci/cico.pipeline
Labels: Crash, High priority, Tests

#2873 Force the commit_we_are_testing branch in CI.
  devel/ci/cico.pipeline
Labels: Crash, Critical, Tests

#2844 Use --force-rm on bodhi-ci build commands.
  devel/ci/bodhi-ci
Labels: RFE, Tests

#2852 Add a timer feature to bodhi-ci.
  devel/ci/bodhi-ci
Labels: RFE, Tests

#2847 Print bodhi-ci's status report after every job exits.
  devel/ci/bodhi-ci
Labels: RFE, Tests

#2876 Remove mention of the meeting from the README.rst.
  README.rst
Labels: Docs

#2879 Run the integration test job the same way as the other jobs.
  devel/ci/cico.pipeline
Labels: Refactor, Tests

#2878 Fix a crash in bodhi-ci clean.
  devel/ci/bodhi-ci
Labels: Crash, Tests
