Repository fedora-infra/bodhi, pull requests merged in 2019-09, with the labels that each got.

#3486 CI: Test on Fedora 31
  .mergify.yml
  devel/ci/Dockerfile-f31
  devel/ci/bodhi-ci
  devel/ci/cico.pipeline
  devel/ci/integration/bodhi/Dockerfile-f31
Labels: Tests

#3521 remove critpath_karma from the UI
  bodhi/server/models.py
  bodhi/server/templates/fragments.html
  bodhi/server/templates/update.html
Labels: Backwards incompatible

#3411 Remove deprecated search_packages path
  bodhi/server/__init__.py
  bodhi/server/views/search.py
  bodhi/tests/server/views/test_search.py
Labels: Backwards incompatible, Search
