Repository fedora-infra/bodhi, pull requests merged in 2019-08, with the labels that each got.

#3444 Ignore the compose decision in the greenwave consumer.
  bodhi/server/consumers/greenwave.py
  bodhi/tests/server/consumers/test_greenwave.py
Labels: 4.2-backports

#3353 Add option to create/edit updates side tags to CLI
  bodhi/client/__init__.py
  bodhi/client/bindings.py
  bodhi/tests/client/test___init__.py
  docs/user/man_pages/bodhi.rst
Labels: Client, Discussion

#3446 Fix the automatic_updates consumer when the build exists but not in an update
  bodhi/server/consumers/automatic_updates.py
  bodhi/tests/server/consumers/test_automatic_updates.py
Labels: 4.1-backports, 4.2-backports, Crash

#3460 Disable time base auto push to stable if we recieve negative karma.
  bodhi/server/models.py
  bodhi/tests/server/scripts/test_approve_testing.py
Labels: 4.1-backports

#3458 Display the number of updates that passed or ignored gating per release.
  bodhi/server/schemas.py
  bodhi/server/services/releases.py
  bodhi/server/services/updates.py
  bodhi/server/templates/release.html
  bodhi/server/validators.py
  bodhi/tests/server/services/test_updates.py
Labels: 4.2-backports

#3421 Deal with message handler exceptions individually
  bodhi/server/consumers/__init__.py
  bodhi/tests/server/consumers/test_consumers.py
Labels: 4.1-backports, Discussion, reliability

#3474 Allow to configure a release without an override tag.
  bodhi/server/schemas.py
  bodhi/server/validators.py
  bodhi/tests/server/test_validators.py
Labels: 4.2-backports

#3443 Print errors to stderr in command line tools
  bodhi/client/__init__.py
  bodhi/server/push.py
  bodhi/server/scripts/bshell.py
  bodhi/server/scripts/check_policies.py
  bodhi/server/scripts/sar.py
  bodhi/tests/client/test___init__.py
  devel/ci/bodhi-ci
Labels: 4.2-backports, EasyFix

#3462 mark updates not composed by bodhi as pushed when stable
  bodhi/server/scripts/approve_testing.py
  bodhi/tests/server/scripts/test_approve_testing.py
Labels: 4.1-backports, 4.2-backports

#2993 Use Python 3 when provisioning Vagrant with Ansible.
  Vagrantfile
  devel/ansible/playbook.yml
Labels: python3

#3463 allow multiple status params for update list views
  bodhi/server/schemas.py
  bodhi/server/services/updates.py
  bodhi/server/validators.py
  bodhi/tests/server/services/test_updates.py
Labels: 4.2-backports
