Repository fedora-infra/bodhi, pull requests merged in 2019-11, with the labels that each got.

#3669 remove unneeded z-index:999 from masthead
  bodhi/server/static/css/site.css
Labels: WebUI

#3662 Add side tag to update view
  bodhi/server/templates/update.html
  bodhi/tests/server/services/test_updates.py
Labels: WebUI

#3639 Migrate server/test_models.py to PyTest
  bodhi/tests/server/test_models.py
Labels: Tests

#3613 Migrate test_schemas.py to PyTest
  bodhi/tests/server/test_schemas.py
Labels: Tests

#3615 Convert bodhi/tests/server/test_alembic.py to PyTest
  bodhi/tests/server/test_alembic.py
Labels: Tests

#3611 Don't derive test classes in test_bugs.py from BaseTestCase.
  bodhi/tests/server/test_bugs.py
Labels: Tests

#3645 Migrate scripts/test_initializedb.py to PyTest
  bodhi/tests/server/scripts/test_initializedb.py
Labels: Tests

#3617 Migrate test_config.py to pytest
  bodhi/tests/server/test_config.py
Labels: Tests

#3225 Remove dist.upgradepath from site_requirements
  bodhi/server/config.py
  production.ini
Labels: Backwards incompatible

#3688 README fixes
  README.rst
Labels: Docs, EasyFix

#3689 work around slow /latest_candidates calls
  bodhi/server/static/js/update_form.js
Labels: High priority, WebUI

#3674 Migrate tasks/test_composer.py to PyTest
  bodhi/tests/server/tasks/test_composer.py
Labels: Tests

#3719 Fix override edit in UI.
  bodhi/server/templates/override.html
  news/3710.bug
Labels: 5.0-backports

#3763 Adjust the hard-coded artifact type
  bodhi/server/models.py
  bodhi/tests/messages/schemas/test_update.py
  bodhi/tests/server/test_models.py
Labels: 5.0-backports

#3782 Increase the size of an update alias.
  bodhi/server/migrations/versions/ff834fa4f23e_increase_the_update_alias_size.py
  bodhi/server/models.py
  news/3779.bug
Labels: 5.1-backports

#3774 Add back the ability to add abitairy text as a build
  bodhi/server/static/css/site.css
  bodhi/server/static/js/update_form.js
Labels: 5.0-backports, 5.1-backports

#3801 fix typo in latest candidates URL
  bodhi/server/static/js/update_form.js
Labels: 5.0-backports, 5.1-backports

#3796 Fix JS error when removing bug from the list
  bodhi/server/static/js/update_form.js
  news/PR3796.bug
Labels: 5.0-backports, 5.1-backports

#3794 Disable warnings when adding `Security Response` bugs to an update
  bodhi/server/static/js/update_form.js
  news/3789.bug
Labels: 5.0-backports, 5.1-backports
