Repository fedora-infra/bodhi, pull requests merged in 2019-10, with the labels that each got.

#3549 Give a hint that the static files dir is versionned
  apache/bodhi.conf
Labels: EasyFix

#3551 Make sure to flush the database when marking a build as signed
  bodhi/server/consumers/signed.py
Labels: 5.0-backports

#3559 Fix hint in 79ce9f0
  apache/bodhi.conf
Labels: 5.0-backports, EasyFix

#3563 Add the release to the builds created in the auto update consumer.
  bodhi/server/consumers/automatic_updates.py
  bodhi/tests/server/consumers/test_automatic_updates.py
Labels: 5.0-backports

#3568 fix overrides list on public user profile page
  bodhi/server/templates/overrides.html
Labels: 5.0-backports

#3572 Don't upgrade packages when building containers for CI
  devel/ci/Dockerfile-f29
  devel/ci/Dockerfile-f30
  devel/ci/Dockerfile-f31
  devel/ci/Dockerfile-pip
  devel/ci/Dockerfile-rawhide
  devel/ci/integration/bodhi/Dockerfile-f29
  devel/ci/integration/bodhi/Dockerfile-f30
  devel/ci/integration/bodhi/Dockerfile-f31
  devel/ci/integration/bodhi/Dockerfile-pip
  devel/ci/integration/bodhi/Dockerfile-rawhide
Labels: 5.0-backports

#3580 fix using Vagrant options
  Vagrantfile
Labels: Tests

#3550 Move the --user and --password arguments in a group with --openid-api
  bodhi/client/__init__.py
  news/PR3550.feature
Labels: 5.0-backports

#3610 convert test_mail.py to BaseTestCase
  bodhi/tests/server/test_mail.py
Labels: Tests

#3612 Migrate test_validators.py to PyTest.
  bodhi/tests/server/test_validators.py
Labels: Tests

#3614 Update test_clean_old_composes to use Pytest
  bodhi/tests/server/scripts/test_clean_old_composes.py
Labels: Tests

#3628 set update.pushed to true when moved to testing in the signed consumer
  bodhi/server/consumers/signed.py
  bodhi/tests/server/consumers/test_signed.py
  news/3625.bug
Labels: 5.0-backports

#3618 Migrate client/test__init__.py to PyTest.
  bodhi/tests/client/test___init__.py
Labels: Tests

#3544 Move multi build update that failed to merge in rawhide to pending.
  bodhi/server/scripts/approve_testing.py
  bodhi/server/tasks/updates.py
  bodhi/tests/server/scripts/test_approve_testing.py
  bodhi/tests/server/tasks/test_updates.py
  news/3514.feature
Labels: 5.0-backports

#3657 Fix a XSS issue
  bodhi/server/templates/fragments.html
  bodhi/server/templates/new_update.html
  bodhi/server/templates/update.html
  bodhi/tests/server/services/test_updates.py
Labels: 4.1-backports, 4.2-backports, 5.0-backports, HTML, High priority, Hotfixed

#3643 Migrate server/test__init__.py to PyTest
  bodhi/tests/server/test___init__.py
Labels: Tests

#3616 Migrate client/test_bindings.py to PyTest
  bodhi/tests/client/test_bindings.py
Labels: Tests

#3666 Make sure to remove the candidate tag for rawhide updates.
  bodhi/server/scripts/approve_testing.py
  bodhi/tests/server/scripts/test_approve_testing.py
Labels: 5.0-backports
