Repository fedora-infra/bodhi, pull requests merged in 2019-06, with the labels that each got.

#3301 Avoid sphinx >= 2.1 in the pip CI test
  devel/ci/Dockerfile-pip
Labels: Crash, Critical, Docs

#3178 Annotate bodhi.client.bindings.
  bodhi/client/bindings.py
  bodhi/tests/client/test_bindings.py
  devel/ci/bodhi-ci
  setup.cfg
Labels: Docs, Refactor

#3283 Use flake8-import-order to enforce PEP-8 imports
  bodhi/client/__init__.py
  bodhi/client/bindings.py
  bodhi/server/bugs.py
  bodhi/server/migrations/env.py
  bodhi/server/models.py
  bodhi/server/scripts/approve_testing.py
  bodhi/server/scripts/clean_old_composes.py
  bodhi/server/scripts/expire_overrides.py
  bodhi/server/scripts/initializedb.py
  bodhi/server/scripts/untag_branched.py
  bodhi/server/security.py
  bodhi/server/services/overrides.py
  bodhi/server/util.py
  bodhi/server/validators.py
  bodhi/tests/server/consumers/test_composer.py
  bodhi/tests/server/consumers/test_updates.py
  devel/ansible/roles/bodhi/tasks/main.yml
  devel/ci/Dockerfile-pip
  devel/ci/integration/tests/test_bodhi.py
  devel/ci/integration/tests/test_bodhi_cli.py
  setup.cfg
  setup.py
Labels: Refactor, Tests

#3289 Correct grammar on a comment that Bodhi writes
  bodhi/server/models.py
  bodhi/tests/server/scripts/test_check_policies.py
  bodhi/tests/server/services/test_updates.py
  bodhi/tests/server/test_models.py
Labels: Refactor

#3299 Convert the client to use f-strings
  bodhi/client/__init__.py
Labels: Client, Refactor

#3309 Correct a message type causing missing coverage
  .coveragerc
  bodhi/tests/server/consumers/test_updates.py
Labels: Tests

#3308 Install command empty string
  bodhi/server/models.py
  bodhi/server/templates/update.html
  bodhi/tests/server/test_models.py
Labels: Refactor

#3321 Don't raise Exception on non-existing composes.
  bodhi/server/consumers/composer.py
  bodhi/tests/server/consumers/test_composer.py
Labels: 4.0-backports, Composer, Crash, Critical, Hotfixed

#3322 Retry on koji.AuthError with backoff
  bodhi/server/buildsys.py
  bodhi/tests/server/test_buildsys.py
  setup.cfg
Labels: Crash, High priority, reliability

#3324 Fix downloading packages for updates with multiple builds
  bodhi/client/__init__.py
  bodhi/tests/client/test___init__.py
Labels: 4.0-backports, Client, Crash, Critical

#3331 Convert the BRO schema to use f-strings
  bodhi/messages/schemas/buildroot_override.py
Labels: Low Priority, Refactor, python3

#3334 Prepare for the upcoming 4.1 release
  .mergify.yml
  docs/conf.py
  docs/user/release_notes.rst
  setup.py
Labels: 4.1-backports

#3275 Clarify the meaning of atomic commits
  docs/developer/index.rst
Labels: Docs

#3181 Docs: Brief overview of the server components.
  docs/administration.rst
Labels: Docs, RFE

#3310 3282
  bodhi/server/models.py
  bodhi/tests/server/scripts/test_approve_testing.py
  bodhi/tests/server/test_models.py
Labels: High priority, Refactor, Tests, WebUI

#3336 Rename bteststyle to blint
  devel/ansible/roles/bodhi/files/.bashrc
  devel/ansible/roles/bodhi/files/motd
Labels: Refactor

#3347 Authorize null mandatory days in testing
  bodhi/server/models.py
  bodhi/tests/server/test_models.py
Labels: 4.1-backports

#3228 API: Create/edit updates from Koji tags
  bodhi/server/buildsys.py
  bodhi/server/migrations/versions/d3f8bd499ecd_add_from_tag_column_to_updates.py
  bodhi/server/models.py
  bodhi/server/schemas.py
  bodhi/server/services/updates.py
  bodhi/server/validators.py
  bodhi/tests/server/base.py
  bodhi/tests/server/services/test_updates.py
  bodhi/tests/server/test_validators.py
  bodhi/tests/server/views/test_generic.py
Labels: API, Migration, RFE

#3342 Convert bodhi.server.bugs to use f-strings
  bodhi/server/bugs.py
Labels: Refactor, bugzilla, python3

#3349 approve_testing needs to setup the buildsystem.
  bodhi/server/scripts/approve_testing.py
Labels: 4.1-backports

#3355 updates: fix typo regarding the from_tag parameter
  bodhi/server/validators.py
  bodhi/tests/server/test_validators.py
Labels: API, EasyFix
