Repository fedora-infra/bodhi, pull requests merged in 2019-12, with the labels that each got.

#3712 util/generate_changelog: Build#get_latest can return None
  bodhi/server/util.py
  bodhi/tests/server/test_util.py
Labels: 5.1-backports, Crash, High priority

#3775 make bodhi comments render as markdown (again)
  bodhi/server/templates/fragments.html
Labels: 5.0-backports, 5.1-backports

#3829 Manage single build update conflicting builds.
  bodhi/server/scripts/approve_testing.py
  bodhi/tests/server/scripts/test_approve_testing.py
  news/3828.bug
Labels: 5.1-backports

#3817 [5.1-Backports] Correctly handle bug titles with double quote in new update form
  bodhi/server/templates/new_update.html
  bodhi/server/util.py
  bodhi/tests/server/test_util.py
  news/3714.bug
Labels: 5.1-backports
