Repository fedora-infra/bodhi, pull requests merged in 2019-07, with the labels that each got.

#3340 Add type hinting to bodhi.server.config
  bodhi/server/config.py
  devel/ci/bodhi-ci
  setup.cfg
Labels: Docs, Refactor, Tests, python3

#3335 Run mypy directly in Vagrant
  devel/ansible/roles/bodhi/files/.bashrc
  devel/ansible/roles/bodhi/tasks/main.yml
  devel/ci/bodhi-ci
  setup.cfg
Labels: Refactor

#3377 Automatically create the rawhide updates in a TESTING state
  bodhi/server/consumers/automatic_updates.py
  bodhi/tests/server/consumers/test_automatic_updates.py
Labels: 4.1-backports

#3379 Change the tag flow in bodhi for rawhide.
  bodhi/server/consumers/automatic_updates.py
  bodhi/tests/server/consumers/test_automatic_updates.py
Labels: 4.1-backports

#3392 When marking the update as stable set the date_stable as well
  bodhi/server/scripts/approve_testing.py
  bodhi/tests/server/scripts/test_approve_testing.py
Labels: 4.1-backports

#3394 Go to stable directly for rawhide-like releases.
  bodhi/server/scripts/approve_testing.py
  bodhi/tests/server/scripts/test_approve_testing.py
Labels: 4.1-backports

#3397 Fix automatically create gated updates if gating is on
  bodhi/server/consumers/automatic_updates.py
  bodhi/tests/server/consumers/test_automatic_updates.py
Labels: 4.1-backports

#3402 Ensure correct order of automatic update comments
  bodhi/server/consumers/automatic_updates.py
  bodhi/tests/server/consumers/test_automatic_updates.py
Labels: 4.1-backports

#3405 Use current feedgen API
  bodhi/server/renderers.py
  requirements.txt
Labels: 4.1-backports, EasyFix, Low Priority

#3418 Ensure pip is available in integration tests
  devel/ci/integration/bodhi/Dockerfile-f29
  devel/ci/integration/bodhi/Dockerfile-f30
  devel/ci/integration/bodhi/Dockerfile-pip
  devel/ci/integration/bodhi/Dockerfile-rawhide
Labels: 4.1-backports, Tests

#3417 Handle situation where there is an existing update but in Pending
  bodhi/server/consumers/automatic_updates.py
  bodhi/tests/server/consumers/test_automatic_updates.py
Labels: 4.1-backports
