Repository fedora-infra/bodhi, pull requests merged in 2019-01, with the labels that each got.

#2891 Happy New Year!
  bodhi/tests/server/scripts/test_sar.py
  bodhi/tests/server/services/test_updates.py
Labels: Crash, Critical, Tests

#2893 Conditionally assert the Request: line in the CLI.
  devel/ci/integration/tests/test_bodhi_cli.py
Labels: Crash, Critical, Tests

#2820 Allow CLI users to override the OpenID API.
  bodhi/client/__init__.py
  bodhi/client/bindings.py
  bodhi/tests/client/test___init__.py
  bodhi/tests/client/test_bindings.py
  devel/ansible/roles/bodhi/files/.bashrc
  devel/development.ini.example
  docs/developer/vagrant.rst
Labels: Client, RFE

#2882 Configure Mergify to use the Bodhi team.
  .mergify.yml
Labels: RFE, Tests

#2868 Prepare for the Bodhi 4.0.0 release.
  docs/conf.py
  docs/user/2.x_release_notes.rst
  docs/user/3.x_release_notes.rst
  docs/user/release_notes.rst
  setup.py
Labels: Docs, High priority, Refactor

#2916 Mark the version as 3.13.
  devel/ci/bodhi-ci
  devel/ci/cico.pipeline
  docs/conf.py
  setup.py
Labels: High priority

#2917 Add release notes for 3.13.
  docs/user/3.x_release_notes.rst
Labels: 3.13-backports, Docs, High priority

#2652 Remove bodhi manage releases
  bodhi/server/scripts/manage_releases.py
  bodhi/tests/server/scripts/test_manage_releases.py
  docs/conf.py
  docs/user/3.x_release_notes.rst
  docs/user/man_pages/bodhi-manage-releases.rst
  docs/user/man_pages/index.rst
  docs/user/release_notes.rst
  setup.py
Labels: Backwards incompatible, Refactor, Server CLI

#2899 Remove the /admin/ API.
  bodhi/server/views/admin.py
  bodhi/tests/server/functional/test_admin.py
  docs/server_api/admin.rst
  docs/server_api/index.rst
  docs/user/release_notes.rst
Labels: API, Backwards incompatible, Refactor

#2907 Kill the /masher view
  bodhi/server/__init__.py
  bodhi/server/static/js/masher-status.js
  bodhi/server/templates/masher.html
  bodhi/server/templates/master.html
  bodhi/server/views/generic.py
  bodhi/tests/server/views/test_generic.py
  docs/user/release_notes.rst
Labels: Backwards incompatible

#2908 Drop support for active_releases from the updates query API
  bodhi/client/__init__.py
  bodhi/client/bindings.py
  bodhi/server/schemas.py
  bodhi/server/services/updates.py
  bodhi/server/templates/updates.html
  bodhi/server/templates/user.html
  bodhi/tests/client/test___init__.py
  bodhi/tests/server/services/test_updates.py
  docs/user/man_pages/bodhi.rst
  docs/user/release_notes.rst
Labels: Backwards incompatible

#2905 Remove bodhi-monitor-composes
  bodhi/server/scripts/monitor_composes.py
  bodhi/tests/server/scripts/test_monitor_composes.py
  docs/conf.py
  docs/user/3.x_release_notes.rst
  docs/user/man_pages/bodhi-monitor-composes.rst
  docs/user/man_pages/index.rst
  docs/user/release_notes.rst
  setup.py
Labels: Backwards incompatible

#2906 zxDrop bodhi.server.services.zz_redirects
  bodhi/server/services/zz_redirects.py
  bodhi/tests/server/services/test_updates.py
  docs/server_api/updates.rst
  docs/user/release_notes.rst
Labels: Backwards incompatible

#2912 Update the copyright in the UI footer.
  bodhi/server/templates/master.html
Labels: HTML, WebUI

#2900 Fix a typo in a test comment.
  bodhi/tests/server/test_util.py
Labels: Docs, Tests

#2897 Bodhi's tests do not use pyyaml.
  devel/ci/Dockerfile-f28
  devel/ci/Dockerfile-f29
  devel/ci/Dockerfile-pip
  devel/ci/Dockerfile-rawhide
  setup.py
Labels: Refactor, Tests

#2933 Fetch all branches during CI.
  devel/ci/bodhi-ci
  devel/ci/cico.pipeline
Labels: Crash, Critical, Tests

#2901 Add some more type annotations to bodhi-ci.
  devel/ci/bodhi-ci
Labels: Refactor, Tests

#2925 Document that Bodhi 3.13.0 requires fedora_messaging.
  docs/user/3.x_release_notes.rst
Labels: 3.13-backports, Docs

#2910 Do not reference the rawhide-modular repo in the pip container.
  devel/ci/Dockerfile-pip
Labels: Refactor, Tests

#2935 Add type annotations and enforcement for bodhi.server.bugs.
  bodhi/server/bugs.py
  devel/ci/bodhi-ci
  setup.cfg
Labels: Refactor, Tests
