Repository fedora-infra/bodhi, pull requests merged in 2019-03, with the labels that each got.

#2914 Compare strings to strings to in Greenwave decision in web UI.
  bodhi/server/templates/update.html
  bodhi/tests/server/services/test_updates.py
Labels: WebUI

#3055 Add Fedora 30 to the CI Greenwave policy.
  devel/ci/integration/greenwave/policy.yaml
Labels: Crash, Critical, Tests

#2967 Add flatpak release type to regex in release.version_int
  bodhi/server/models.py
  bodhi/tests/server/test_models.py
Labels: 3.13-backports, Crash, High priority

#2985 Remove obsolete scripts from tools folder
  docs/user/release_notes.rst
  tools/fix-testing-updates.py
  tools/metrics.py
  tools/perf-test.py
  tools/python-fedora-api-test.py
  tools/shelldb.py
Labels: Backwards incompatible

#2940 Trim all database migrations prior to the head of 3.13.0.
  bodhi/server/migrations/versions/06aa0e8aa5d2_drop_the_update_karma_column.py
  bodhi/server/migrations/versions/0e105f6e36b4_add_an_scm_url_column_to_the_builds_table.py
  bodhi/server/migrations/versions/12d3e8695f90_drop_the_unused_inherited_column_from_.py
  bodhi/server/migrations/versions/22858ba91115_add_new_side_tag_update_states.py
  bodhi/server/migrations/versions/2616c86d8ac6_add_indexes_for_status_and_request.py
  bodhi/server/migrations/versions/2a10629168e4_add_request_for_batched_update.py
  bodhi/server/migrations/versions/2c5d45f0c932_add_a_new_state_for_cleaning_composes.py
  bodhi/server/migrations/versions/33a416e03f50_add_greenwave_fields.py
  bodhi/server/migrations/versions/385acbb51075_add_flatpak_enum.py
  bodhi/server/migrations/versions/39132c56a47e_drop_uniqueness_constraint_on_user_email.py
  bodhi/server/migrations/versions/3a14c47250fb_add_a_private_flag_to_bugs.py
  bodhi/server/migrations/versions/4b357c65441e_add_ci_status_to_builds.py
  bodhi/server/migrations/versions/4ed8554a4fc9_add_the_new_compose_model.py
  bodhi/server/migrations/versions/4f2f825bcf4a_disallow_null_values_in_autokarma.py
  bodhi/server/migrations/versions/59c0f5fbc1b2_add_a_greenwave_unsatisfied_.py
  bodhi/server/migrations/versions/630acb5218a4_make_updates_release_id_non_nullable.py
  bodhi/server/migrations/versions/68f9ccb1f388_add_a_syncing_repo_composestate_enum_.py
  bodhi/server/migrations/versions/74cfbc6116ad_add_packages_type_constraint.py
  bodhi/server/migrations/versions/865d9432fa7d_build_package_id_is_now_required.py
  bodhi/server/migrations/versions/8eaacb38b036_add_the_ci_url_field_to_builds.py
  bodhi/server/migrations/versions/9241378c92ab_convert_the_builds_table_to_be_.py
  bodhi/server/migrations/versions/95ce24bed77a_remove_the_ci_status_feature.py
  bodhi/server/migrations/versions/adee0d22d09f_drop_the_uniqueness_constraint_on_.py
  bodhi/server/migrations/versions/b01a62d98aa4_convert_package_and_build_type_columns_.py
  bodhi/server/migrations/versions/be25565a1211_add_a_dislay_name_field_to_the_updates_.py
  bodhi/server/migrations/versions/c21dd18b161a_add_a_new_signing_repo_composestate_enum.py
  bodhi/server/migrations/versions/c6a5e2849ca4_add_a_uniqueness_constraint_on_name_.py
  bodhi/server/migrations/versions/d986618207bc_add_composed_by_bodhi_flag_to_releases_.py
  bodhi/server/migrations/versions/da710ff02641_add_container_enum.py
  bodhi/server/migrations/versions/ebaab70b2cda_added_field_to_store_mail_template_.py
  bodhi/server/migrations/versions/fc6b0169c596_add_a_column_for_single_table_.py
  docs/user/release_notes.rst
Labels: Backwards incompatible, Migration, Refactor

#2987 Drop support for Python 2.
  .mergify.yml
  bodhi/client/__init__.py
  bodhi/client/bindings.py
  bodhi/tests/client/test___init__.py
  bodhi/tests/client/test_bindings.py
  bodhi/tests/server/__init__.py
  bodhi/tests/server/base.py
  bodhi/tests/server/consumers/test_composer.py
  bodhi/tests/server/consumers/test_signed.py
  bodhi/tests/server/consumers/test_updates.py
  bodhi/tests/server/functional/test_users.py
  bodhi/tests/server/scripts/test_approve_testing.py
  bodhi/tests/server/scripts/test_bshell.py
  bodhi/tests/server/scripts/test_check_policies.py
  bodhi/tests/server/scripts/test_clean_old_composes.py
  bodhi/tests/server/scripts/test_expire_overrides.py
  bodhi/tests/server/scripts/test_initializedb.py
  bodhi/tests/server/scripts/test_sar.py
  bodhi/tests/server/scripts/test_skopeo_lite.py
  bodhi/tests/server/scripts/test_untag_branched.py
  bodhi/tests/server/services/test_comments.py
  bodhi/tests/server/services/test_errors.py
  bodhi/tests/server/services/test_overrides.py
  bodhi/tests/server/services/test_releases.py
  bodhi/tests/server/services/test_updates.py
  bodhi/tests/server/test___init__.py
  bodhi/tests/server/test_bugs.py
  bodhi/tests/server/test_buildsys.py
  bodhi/tests/server/test_captcha.py
  bodhi/tests/server/test_config.py
  bodhi/tests/server/test_mail.py
  bodhi/tests/server/test_metadata.py
  bodhi/tests/server/test_models.py
  bodhi/tests/server/test_notifications.py
  bodhi/tests/server/test_push.py
  bodhi/tests/server/test_renderers.py
  bodhi/tests/server/test_security.py
  bodhi/tests/server/test_util.py
  bodhi/tests/server/test_validators.py
  bodhi/tests/server/test_webapp.py
  bodhi/tests/server/views/test_generic.py
  devel/ansible/roles/bodhi/tasks/main.yml
  devel/ci/Dockerfile-f28
  devel/ci/Dockerfile-f29
  devel/ci/Dockerfile-pip
  devel/ci/Dockerfile-rawhide
  devel/ci/bodhi-ci
  devel/ci/cico.pipeline
  docs/user/release_notes.rst
  requirements.txt
  setup.py
Labels: Refactor, python3

#2995 Rename prefer_ssl to libravatar_prefer_tls.
  bodhi/server/config.py
  bodhi/server/util.py
  bodhi/tests/server/test_util.py
  docs/user/release_notes.rst
  production.ini
Labels: Backwards incompatible, Refactor

#3006 The CLI now defaults to the BRO --wait flag.
  bodhi/client/__init__.py
  bodhi/tests/client/test___init__.py
  docs/user/release_notes.rst
Labels: Backwards incompatible, Client, RFE

#3000 Document the compose states.
  docs/administration.rst
Labels: Composer, Docs

#3033 Begin integration testing with Fedora 30.
  .mergify.yml
  devel/ci/Dockerfile-f30
  devel/ci/bodhi-ci
  devel/ci/cico.pipeline
  devel/ci/integration/bodhi/Dockerfile-f30
Labels: RFE, Tests

#3043 Link search box results for packages to packages instead of users
  bodhi/server/static/js/search.js
Labels: Critical, JS

#3054 Raise timeout from 30 to 64 in the db test fixture
  devel/ci/integration/tests/fixtures/db.py
Labels: Tests, reliability

#2957 Configure the consumers to use fedora_messaging.
  bodhi/server/consumers/__init__.py
  bodhi/server/consumers/composer.py
  bodhi/server/consumers/signed.py
  bodhi/server/consumers/updates.py
  bodhi/tests/server/consumers/test_composer.py
  bodhi/tests/server/consumers/test_consumers.py
  bodhi/tests/server/consumers/test_signed.py
  bodhi/tests/server/consumers/test_updates.py
  devel/development.ini.example
Labels: Composer, High priority, no-mergify, reliability

#2953 Block creating anonymous comments
  bodhi/client/bindings.py
  bodhi/server/__init__.py
  bodhi/server/captcha.py
  bodhi/server/config.py
  bodhi/server/migrations/versions/c98beb4940b5_remove_the_comments_anonymous_column.py
  bodhi/server/models.py
  bodhi/server/renderers.py
  bodhi/server/schemas.py
  bodhi/server/scripts/sar.py
  bodhi/server/services/comments.py
  bodhi/server/templates/update.html
  bodhi/server/validators.py
  bodhi/tests/client/__init__.py
  bodhi/tests/client/test___init__.py
  bodhi/tests/client/test_bindings.py
  bodhi/tests/server/__init__.py
  bodhi/tests/server/scripts/test_approve_testing.py
  bodhi/tests/server/scripts/test_sar.py
  bodhi/tests/server/services/test_comments.py
  bodhi/tests/server/services/test_updates.py
  bodhi/tests/server/test_captcha.py
  bodhi/tests/server/test_config.py
  bodhi/tests/server/test_models.py
  bodhi/tests/server/test_renderers.py
  bodhi/tests/server/test_schemas.py
  bodhi/tests/server/test_validators.py
  devel/ansible/roles/bodhi/tasks/main.yml
  devel/ci/Dockerfile-f28
  devel/ci/Dockerfile-f29
  devel/ci/Dockerfile-f30
  devel/ci/Dockerfile-pip
  devel/ci/Dockerfile-rawhide
  devel/ci/integration/tests/fixtures/bodhi.py
  docs/developer/virtualenv.rst
  docs/user/release_notes.rst
  docs/user/testing.rst
  production.ini
  requirements.txt
Labels: Backwards incompatible

#2842 Add the bodhi_messages Python package
  bodhi/__init__.py
  bodhi/messages/__init__.py
  bodhi/messages/schemas/__init__.py
  bodhi/messages/schemas/base.py
  bodhi/messages/schemas/buildroot_override.py
  bodhi/messages/schemas/compose.py
  bodhi/messages/schemas/composer.py
  bodhi/messages/schemas/errata.py
  bodhi/messages/schemas/update.py
  bodhi/messages/utils.py
  bodhi/server/ffmarkdown.py
  bodhi/tests/messages/__init__.py
  bodhi/tests/messages/schemas/__init__.py
  bodhi/tests/messages/schemas/test_buildroot_override.py
  bodhi/tests/messages/schemas/test_compose.py
  bodhi/tests/messages/schemas/test_composer.py
  bodhi/tests/messages/schemas/test_errata.py
  bodhi/tests/messages/schemas/test_update.py
  bodhi/tests/messages/utils.py
  devel/ci/bodhi-ci
  docs/user/release_notes.rst
  setup.cfg
  setup.py
Labels: Critical, RFE

#3103 Fix the alignment of the test names.
  devel/ci/bodhi-ci
Labels: Tests

#3116 Document that type hinting should be used.
  docs/developer/index.rst
Labels: Docs
