Repository fedora-infra/bodhi, pull requests merged in 2019-02, with the labels that each got.

#2915 Drop support for CVEs.
  bodhi/client/__init__.py
  bodhi/client/bindings.py
  bodhi/server/mail.py
  bodhi/server/metadata.py
  bodhi/server/migrations/versions/5c86a3f9dc03_drop_support_for_cve_tracking.py
  bodhi/server/models.py
  bodhi/server/schemas.py
  bodhi/server/services/updates.py
  bodhi/tests/client/test___init__.py
  bodhi/tests/server/__init__.py
  bodhi/tests/server/consumers/test_masher.py
  bodhi/tests/server/services/test_updates.py
  bodhi/tests/server/test_metadata.py
  bodhi/tests/server/test_models.py
  docs/user/man_pages/bodhi.rst
  docs/user/release_notes.rst
Labels: API, Backwards incompatible, Client, Migration, Refactor

#2931 Document the mail.templates_basepath setting.
  production.ini
Labels: Docs

#2981 Download database dumps first in CentOS CI
  devel/ci/bodhi-ci
  devel/ci/cico.pipeline
Labels: Crash, High priority, Tests

#2984 Use a UUID in the test network name.
  devel/ci/integration/tests/fixtures/backend.py
Labels: Crash, Tests

#2986 Avoid deadlock when database downloads are old.
  devel/ci/bodhi-ci
Labels: Crash, High priority, Tests

#2990 Use a setting to configure the fedmsg-hub WS URL.
  bodhi/server/config.py
  bodhi/server/static/js/live.js
  bodhi/server/templates/master.html
  production.ini
Labels: Crash, JS, WebUI

#2997 Add an apostrophe for a possessive in a comment.
  bodhi/server/mail.py
Labels: Docs, Low Priority

#2996 Remove a stray debugging statement from site.js.
  bodhi/server/static/js/site.js
Labels: JS, Low Priority, Refactor

#3002 Explicitly require psycopg2.
  devel/ci/Dockerfile-f28
  devel/ci/Dockerfile-f29
  devel/ci/Dockerfile-rawhide
  devel/ci/integration/bodhi/Dockerfile-f28
  devel/ci/integration/bodhi/Dockerfile-f29
  devel/ci/integration/bodhi/Dockerfile-pip
  devel/ci/integration/bodhi/Dockerfile-rawhide
  requirements.txt
Labels: 3.13-backports, Crash, High priority

#2918 Document the release process.
  docs/developer/releases.rst
  docs/index.rst
Labels: Docs

#2994 Drop the batching feature.
  bodhi/client/__init__.py
  bodhi/client/bindings.py
  bodhi/server/config.py
  bodhi/server/migrations/versions/190ba571c7d2_remove_the_batching_request_state.py
  bodhi/server/models.py
  bodhi/server/scripts/dequeue_stable.py
  bodhi/server/services/updates.py
  bodhi/server/static/js/update_form.js
  bodhi/server/templates/new_update.html
  bodhi/server/templates/update.html
  bodhi/server/util.py
  bodhi/server/validators.py
  bodhi/tests/server/consumers/test_masher.py
  bodhi/tests/server/scripts/test_dequeue_stable.py
  bodhi/tests/server/services/test_updates.py
  bodhi/tests/server/test_models.py
  bodhi/tests/server/test_util.py
  docs/conf.py
  docs/user/3.x_release_notes.rst
  docs/user/man_pages/bodhi-dequeue-stable.rst
  docs/user/man_pages/index.rst
  docs/user/release_notes.rst
  docs/user/update_states.rst
Labels: API, Backwards incompatible, High priority, Migration, Refactor

#3003 Specify only a minimum version on Pyramid.
  requirements.txt
Labels: Refactor

#3012 Compare enum values instead of descriptions.
  bodhi/server/templates/new_update.html
  bodhi/server/templates/update.html
Labels: HTML, Refactor

#3018 Vagrant: Fold bdiff-cover into btest.
  devel/ansible/roles/bodhi/files/.bashrc
  devel/ansible/roles/bodhi/files/motd
Labels: Tests

#3030 Prepare for the 3.13.2 release.
  docs/user/3.x_release_notes.rst
Labels: 3.13-backports, Docs, High priority

#3026 Remove misplaced variable in the update template
  bodhi/server/templates/update.html
Labels: 3.13-backports, HTML

#3034 Add static type checking to bodhi.server.buildsys.
  bodhi/server/buildsys.py
  bodhi/tests/server/test_buildsys.py
  devel/ci/bodhi-ci
  setup.cfg
Labels: Refactor
